---
openapi: 3.0.2
info:
  title: ingestion
  version: 1.2.0
servers:
- url: http://localhost:8080/v1.2.0
  description: ""
- url: https://ingestion.mint.isi.edu/v1.2.0
  description: ""
paths:
  /modelthreads:
    summary: Path used to manage the list of modelthreads.
    description: The REST endpoint/path used to list and create zero or more `modelthread`
      entities.  This path contains a `GET` and `POST` operation to perform the list
      and create tasks, respectively.
    post:
      requestBody:
        description: A new `modelthread` to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelthread'
        required: true
      responses:
        "201":
          description: Successful response.
      operationId: createmodelthread
      summary: Create a modelthread
      description: Creates a new instance of a `modelthread`.
    get:
      parameters:
      - name: limit
        description: ""
        schema:
          type: integer
          maximum: 500
          default: 200
        required: true
        in: query
      - name: page
        description: ""
        schema:
          type: integer
          default: 1
        in: query
      - name: model
        description: ""
        schema:
          type: string
        in: query
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/thread'
          description: Successful response - returns an array of `thread` entities.
      operationId: getthreads
      summary: List All threads
      description: Gets a list of all `thread` entities.
      tags:
        - thread
  /modelthreads/{thread_id}:
    get:
      description: Gets the details of a single instance of a Thread
      parameters:
      - description: The ID of the resource
        in: path
        name: thread_id
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/thread'
          description: Gets the details of a single instance of Thread
      summary: Get a Thread
      tags:
      - thread
  /summary:
    summary: Obtain the summary of a modelthead
    description: Obtain the summary of a modelthead
    post:
      requestBody:
        description: Obtain a `summary`
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        "201":
          description: Successful response.
      operationId: get_summary
      summary: Create a summary
      description: Creates a new instance of a `modelthread`.
components:
  schemas:
    modelthread:
      description: ""
      required:
      - scenario_id
      - subgoal_id
      - thread_id
      type: object
      properties:
        scenario_id:
          description: ""
          type: string
        subgoal_id:
          description: ""
          type: string
        thread_id:
          description: ""
          type: string
    thread:
      description: ""
      type: object
      properties:
        id:
          description: ""
          type: string
        text:
          description: ""
        time_period:
          description: ""
        indicators:
          description: ""
        models:
          description: ""
        datasets:
          description: ""
        results:
          description: ""
